qlik-oss/corectl

- internal/modeldata.go
Earlier there were no check if `GetLayout` returned an error when fetching a system table.
> Exit on error when fetching system table

- README.md
- internal/eval.go
Earlier there was no error handling when failing to evaluate an expression, and the documentation was also incorrect.
> Add error handling for failed evalulations

- README.md
- buildtohomebin
- internal/eval.go
- internal/eval_test.go
It's now possible to evaluate an expression regardless of dimension using the `*`. Also added some more examples to the readme.
> eval: Handle when iterating over all dimensions

- main.go
If typing an incorrect command or printing help instructions showed the old tool name.
> Rename usage instructions from qli to corectl

- README.md
- internal/eval.go
- internal/field.go
- internal/modeldata.go
- internal/restapi.go
- internal/script.go
- internal/state.go
- main.go
- printer/status.go
- test/corectl_integration_test.go
- test/golden/project3-fields.golden
- test/golden/project3-reload.golden
- test/project3/qli.yml
- test/project3/script.qvs
Fixes #34, #30, #17
- Added a check that there is at least one table in all view commands (fields, eval etc)
- Made session id more unique (but still persistent) not to clash if more than one user accesses the same engine
- No more accidental creation of unnamed apps. If no app is specified a session app is used.
- Added a new status command which sometimes is needed to understand issues where corectl is accidentally connected to the wrong engine or wrong app (for instance when pointing at the wrong config file).
> Improved error handling and a bonus status command

- docs/corectl_reload.md
- internal/reload.go
- main.go
- test/corectl_integration_test.go
- test/golden/project1-reload-silent.golden
- test/golden/project1-reload.golden
- test/golden/project3-reload.golden
Earlier the reload progress was tied to the `--verbose` flag which enabled more than just reload progress logging. This PR adds a `--silent` flag for the `reload` command for opting out of reload progress. By default the reload progress logging will be enabled.
> Add silent flag for opting out of reload progress

- .circleci/config.yml
Tags needs to be whitelisted and not blacklisted to run.
> Update release flow

- internal/modeldata.go
- internal/systemtable.go
This fixes #122
Now you get the same tables that you get in Qlik Sense
There seems to be a mismatch between the tables that are included by using `GetTableAndKeys` and when using this hypercube
```
object, _ := doc.CreateSessionObject(ctx, &enigma.GenericObjectProperties{
Info: &enigma.NxInfo{
Type: "my-pivot-hypercube",
},
HyperCubeDef: &enigma.HyperCubeDef{
Dimensions: []*enigma.NxDimension{
{
Def: &enigma.NxInlineDimensionDef{
FieldDefs:     []string{"=$Field"},
SortCriterias: []*enigma.SortCriteria{{SortByExpression: -1, Expression: &enigma.ValueExpr{V: "=count($Table)"}}},
},
},
{
Def: &enigma.NxInlineDimensionDef{
FieldDefs:     []string{"=$Table"},
SortCriterias: []*enigma.SortCriteria{{SortByExpression: -1, Expression: &enigma.ValueExpr{V: "=count($Field)"}}},
},
},
},
Measures: …
```
> Only use the table names from "GetTableAndKeys"

- cmd/utils.go
- go.mod
- go.sum
This PR adds a check for latest release on github when running the `version` command. Will only be executed on binaries built with a `main.version`.  Will also generate a download string based on OS and executable path to update the tool.
```
➜  corectl git:(latest) go build -ldflags "-X main.version=0.2.0" -o corectl main.go
➜  corectl git:(latest) ./corectl version
-------------------------------------------------
Version 0.2.0 is not latest, you should upgrade to 0.4.0 
To download the latest version you can use this command: 
'curl --silent --location "https://github.com/qlik-oss/corectl/releases/download/v0.4.0/corectl-darwin-x86_64.tar.gz" | tar xz -C /tmp && mv /tmp/corectl /Users/mow/gits/qlik-oss/corectl'
-------------------------------------------------
corectl version: 0.2.0 …
```
> Check for latest release when running the version command

- internal/connections.go
If a connection string was set in a config it was not possible to configure a user or password. It should be up to the engine to validate the connection parameters being passed in.
> Fix for being unable to set user and password for a connection in config

- docs/corectl_config.md
- internal/connections.go
Earlier we did not append a semicolon at the end of a `connectionstring` when appending settings. This led to reload errors when e.g. using custom connectors. Also added some additional documentation regarding how the `settings` can be used.
This closes #167
> Append semicolon when flattening settings for a connection

- internal/state.go
If `qSuccess` was false when creating an app, no error was logged. Happens if e.g. engine has insufficient rights to write in a mounted folder.
> Trigger fatal if app creation fails

- cmd/root.go
- printer/apps.go
- printer/connections.go
- printer/entities.go
`compgen` did not handle filenames containing whitespaces very well, so we will set the `COMPREPLY`directly. We also need to quote all strings that contains a whitespace.
Related to #170
> Handle filenames with spaces during autocompletion

- .circleci/config.yml
- cmd/get.go
- cmd/remove.go
- cmd/set.go
- cmd/utils.go
- internal/knownapps.go
- internal/reload.go
- internal/state.go
- printer/status.go
- test/corectl_integration_test.go
- test/docker-compose.yml
- test/golden/project4-meta.golden
- test/project4/corectl.yml
- test/project4/script.qvs
- test/rules/rules.txt
This PR adds persisting of app IDs when creating apps using `corectl`. When using an engine with ABAC we should use the app ID when opening a session to an app, and not the app name. If an id does not exist in the knownApps file we assume that appID = appName.
Also changed so only `build` and `set` commands actually creates an app, if one does not already exist.
This closes #178
> Persist known app IDs to support creation of apps when using ABAC

- go.mod
- go.sum
- internal/config.go
- test/corectl_integration_test.go
Related to the config validation we now provide some feedback in the form of suggestions for property names that are likely typos and more thorough feedback for erroneous configs in general.
Exactly what Levenshtein distance between two words we define as a typo is up for debate. I made the arbitrary choice of distance 4 as limit, using the default option in the Levenshtein library which weighs inserts and deletions as 1 and substitutions as 2.
The feedback also references the yaml's absolute path.
This close the issue #204
> Suggestion typos

- cmd/flags.go
- internal/config.go
Valid properties are no longer hard coded.
They are instead added dynamically in the `cmd/flags.go` file.
I figured that `validProps` should be private since I can't see any reason this would be needed elsewhere.
> Valid properties are now dynamically added

- cmd/build.go
- cmd/connection.go
- cmd/dimension.go
- cmd/flags.go
- cmd/measure.go
- cmd/object.go
- internal/config.go
- internal/connections.go
- internal/entities.go
- internal/helpers.go
- internal/helpers_test.go
Changed so that config information is retrieved from viper instead of use `yaml.Unmarshal` here and there throughout the project.
Main changes are:
- `internal.ConfigDir` stores the directory of the current config file
- The config file is read once
- `internal/config.go` handles the config files
With this change, we will be able to substitute environment variables in config files and work towards resolving: #206 and #197. (There is another PR in the chamber with that enhancement.)
> Unmarshal fix

- cmd/root.go
- cmd/script.go
- docs/corectl_script_set.md
- internal/config.go
Pretties prints for invalid syntax in configs.
No duplicate error messages.
Script set usage fixed.
Closes #219 
Closes #223 
Closes #228
> Small output fixes

- cmd/app.go
- internal/knownapps.go
- internal/state.go
This PR changes so that before attempting to delete an app it checks whether or not such an app exists.
Mainly so that the user does not have to confirm something that can't happen.
> Check if app exists before rm confirmation

- LICENSE
During the refactoring of the command structure the completion implementation was moved to a separate file. We also need to update the license file with the new path.
> Update license file with path to completion

- cmd/completion.go
This PR adds bash/zsh completion for the `rm` command in `object`, `connection`, `app`, `dimension` and `measure`.
This closes #222
> Add bash completion for rm commands

- .circleci/config.yml
This PR adds a Circle CI step for validating the api specification towards the schema using `ajv`.
This closes #240
> Validate api specification towards schema in Circle CI

- cmd/app.go
- internal/state.go
- internal/state_test.go
Earlier `corectl` always appended `/app/engineData/ttl/<ttl>` to an engine url which led to incorrect behaviour when e.g. connecting to Qlik Sense Enterprise. Changed so that we only modify the url if it does not contain a path. Also if no app name is provided `corectl` will check if one is present in the url.
This closes #193
> Handle websocket urls including paths and app identifiers

- cmd/analyze.go
- internal/state.go
- internal/state_test.go
The `corectl catwalk` command was not working when an app name was provided in the engine url.
> Handle app identifier in websocket url for catwalk command

- renovate.json
Renovate updates dependencies for the go modules, but it does not run `go mod tidy` by default so we need to add it as a `postUpdateOptions`.
This closes #176
> Add go mod tidy to renovate configuration

- README.md
- cmd/bookmark.go
- cmd/build.go
- cmd/generate.go
- cmd/variable.go
- docs/corectl_bookmark.md
- docs/spec.json
- test/corectl_integration_test.go
`bookmark set` is now hidden because a bookmark cannot be fully created through APIs, meaning that the command might not behave as expected.
Also marked variable and bookmark as experimental as well as changed so that `generate-spec` works as `generate-docs`. (You don't have to pipe the output to a file.)
> Hide bookmark set

- cmd/utils.go
- go.mod
- go.sum
Dependency `go-latest` has not been maintained for a while and when renovate tries to update sub-dependencies it often fails. This PR removes `go-latest` and makes use of more notable dependencies `go-github` by Google and `go-version` by Hashicorp instead.
> Remove unmaintained dependency go-latest

- .goreleaser.yml
This PR adds a config for updating the formula in the `homebrew-taps` repo when a new version of corectl is released. I haven't found any way to verify the generated formula locally using snapshot, but the configuration seems fairly straightforward.
Also changed the sections for `archive` and `snapcraft` which were deprecated.
https://goreleaser.com/customization/#Homebrew
> Publish brew tap formula using goreleaser

- cmd/app.go
- internal/knownapps.go
- internal/state.go
Changing functionality from doing lookup and mapping based on the provided engine string to the parsed host of that string instead.
This will change so that a if the provided engine url was `localhost:1234/app/my-app` we will map any apps created using that url to `localhost:1234` instead of the whole url, as we did before.
Closes #338
> Known app lookup based on host

- .circleci/config.yml
`go fmt ./...` installed dependencies in `go.mod` and since we run `git diff` directly after this caused a renovate job to fail. I changed so that any dependencies install by either `go fmt` or `golint` should not interfere with the linting itself.
> Circleci linting fix

- .circleci/config.yml
Identical problem as in #368 but here with `go test` instead. It appears that many go tools use the `go-github` library but have yet to update to the latest version.
> Fixed go.mod and go.sum problem in circleci build step

- test/golden/TestTrafficFlag_script_get_--traffic.golden
The JSON traffic in the integration tests has changed so I have updated the golden file accordingly. Will investigate further why the `warnings` property is appearing, but lets get the master branch green in Circle CI first.
> Update golden file for test

- internal/config.go
When using viper to read string maps, all keys are converted to lower-case. This PR changes so connections are always read from file and not through viper.
This closes #351
> Read connections config from file and not through viper

- cmd/flags.go
- cmd/root.go
- internal/config.go
- internal/context.go
Fixed some issues regarding absolute paths and certificates, as well as changed how the certificate flag is used. It is now used similarly to how the config flag is used.
> Context can now get cert from flags, with abs path

- internal/object.go
- test/golden/TestChildObjectsAndFullPropertyTree_object_ls_--json.golden
When running e.g. the `build` command creation/updating of objects were done sequentially. This PR changes so it is done in parallel instead. Since we want the output of `object ls` to be deterministic, I have also changed so the returned objects are sorted in alphabetical order on `qId`.
This closes #410
> Run SetProperties in parallel when updating multiple objects

- internal/dimension.go
- internal/measure.go
- internal/object.go
- test/corectl_integration_test.go
Similar change that was earlier done for objects. Was not applied to `variables` due to running into problem with aborted requests. Since creating lots of variables through corectl seems like a less common scenario, I will leave it sequential for now.
> Create and update dimensions and measures in parallel

- .goreleaser.yml
The automated image bumps are still present in the release changelog. Looks like the PR number is appended to the squash commit when merged to master.
> chore: Update excluded commits from changelog

- go.sum
- internal/config.go
- internal/log/log.go
- test/corectl_integration_test.go
- test/projects/quiet/corectl.yml
We can now properly log before the config has been read.
Logging rules will be obeyed with the exception of fatal errors occurring before the config has been completely read.
Closes #430
> Add log buffer

- internal/script.go
If failing to set a script we should log the error and exit, this was not handled earlier.
This closes #455
> Fatal if failing to set script

- examples/docker-compose.yml
- internal/unbuilder.go
- internal/unbuilder_test.go
- test/docker-compose.yml
We need to secure that the filename generated when unbuilding objects is unique, otherwise we might override objects that have the same `type` and `title`. This PR adds the `qId` to the filename to secure it being unique on disk.
Another option would be to put all the objects in the same file, similar to how it is done with `dimensions` and `measures`. That could however lead to a very large file depending on the number of objects in an app, and would be harder to edit from source control.
This closes #500
> Append qId to the object file name when unbuilding

- pkg/boot/boot.go
Exposing a boot function that can be used in the case you want to read settings but don't need a communicator.
> Expose separate Boot function

- cmd/root.go
- docs/spec.json
- main.go
- pkg/boot/common_settings.go
- pkg/dynconf/dyn_settings.go
The `User-Agent` will now contain information from the root command: name and version (if specified).
It will also include what OS it is run on.
It will default to `corectl` if for some reason (no root command name) the `User-Agent` cannot be determined nicely.
`corectl` with current dev-version on linux will look like:
```
corectl/1.5.3-dev (linux)
```
> Make user-agent more precise

- pkg/boot/flags.go
- pkg/rest/rest_caller.go
This PR implements curl-like verbose-logging for rest calls.
This entails logging sent and received headers as well as sent payload (in the case it's JSON).
Example:
```
POST https://qcaas.eu.qlikcloud.com/api/v1/csp-origins
> Authorization: Bearer **omitted**
> Content-Type: application/json
> User-Agent: qlik/v0.1.2-dev (linux)
PAYLOAD:
{
"name": "yo"
}
< Cache-Control: no-store
< Connection: keep-alive
< Content-Length: 118
< Content-Type: application/json; charset=utf-8
< Date: Tue, 21 Apr 2020 14:10:12 GMT
< Pragma: no-cache
< Server: openresty
< Strict-Transport-Security: max-age=15724800; includeSubDomains
Time 363.678923ms
400 Bad Request: Failed to create/update CSP entry: Origin cannot be an empty string (CSP-8)
```
> Improve rest debug logs

- pkg/rest/rest_caller.go
Accidentally printing 'PAYLOAD:' even if there is no payload, which looks ugly.
> Cleanup payload logging

- pkg/rest/rest_caller.go
Provide arguments to `HasPrefix` in right order to filter out API-key for readability.
> fix: Bearer omission

- pkg/commands/standard/raw.go
- pkg/rest/rest_caller.go
Check and handle the output-type of responses so we don't print bad stuff directly to the terminal.
> Handle output content-type

- pkg/rest/multireadcloser_test.go
- pkg/rest/rest_caller.go
- pkg/rest/utils.go
Move output related functions to a separate `pkg/rest/utils.go` file. As many of these things are quite generic, we might want to move them somewhere else in the future, and this way we improve the separation of responsibilities a bit.
I also added comments to some functions and quirky bits of code.
> Rest package polish

- pkg/boot/flags.go
- pkg/commands/standard/context.go
- pkg/dynconf/context.go
- pkg/dynconf/dyn_settings.go
- pkg/rest/rest_caller.go
- printer/contexts.go
- test/corectl_integration_test.go
This solves an issue current present which is that headers in context will always be overwritten.
It also adds the ability to put more key-value pairs into the context: any global flag and any flag present on the context command itself can be used as key, except for `config`.
Also "unhides" the `--insecure` flag.
> Context update fix

- internal/entities.go
- internal/object.go
- test/golden/TestChildObjectsAndFullPropertyTree_object_ls_--json.golden
`Title` was never populated when listing objects. This PR changes so we populate `Title` from `qMetaDef/title`.
This closes #534.
> fix: parse title from qMetaDef

- pkg/rest/rest_caller.go
Logging response status if successful and verbose.
Changed the time logging to read:
```
Response time: <time-in-ms>ms
```
> Log response status if verbose

- pkg/rest/app.go
- pkg/rest/app_test.go
Match the known patterns for app IDs, item IDs and regular names so that we only need to make one call to lookup a provided app identifier.
Benefits:
- Makes usage of pure app IDs faster (no extra calls needed).
- When lookups are needed, the debug-logs are still comprehensible since it's only one call and not 3 parallel ones.
*TODO*: Tests.
> Minimize calls needed to interpret app identifier

- pkg/rest/rest_caller.go
If a 201 Created response contains both a body and a location header we will now print the body and not follow the redirect.
> Handle non-empty 201 Created responses with location headers

- pkg/commands/standard/raw.go
- pkg/rest/rest_caller.go
- pkg/rest/utils.go
Adds a functions type:
```
type Filter func([]byte) []byte
```
which can be provided for custom filtering. Also exposing the already present filters for `--quiet`, `--raw` and standard output.
> Enable custom output filtering

- cmd/root.go
- docs/spec.json
- pkg/dynconf/dyn_settings.go
Now version is expected to be supplied as an annotation on the root command instead of as a field.
This is more flexible and probably more in line with the intended use of both these fields (`.Version` and `.Annotations`).
This also has the benefit of removing the small, but present, headache that is the hidden (runtime generated) version flag which supplies incomplete version information.
> Supply version as annotation instead of field

- pkg/commands/standard/raw.go
- pkg/rest/error_parser.go
- pkg/rest/rest_caller.go
Adds an `Error` interface to the package which contains a method to check what the status code of the response was.
> Improve error handling in pkg/rest

- docs/spec.json
- pkg/commands/standard/generate.go
If flags are annotated with `x-qlik-stability` and `x-qlik-visibility` it will be part of the resulting CLI specification as well.
> Update spec to include visibility and stability for flags

- .circleci/config.yml
- examples/docker-compose.yml
- test/docker-compose.yml
* Removes schema validation for the API specification since it is no longer available.
* Bumps engine docker version to `12.925.0`
> fix: skip schema validation of spec and bump engine version
