printer/fields.go
test/output/project1-fields.txt
test/output/project2-fields.txt

Add newlines after printing fields

---

.gitignore
main.go
test/corectl_integration_test.go
test/project2/connections.yml

Update to have the same name both doc and implementation for connections file.

Update connections file target, integrationtest to show without config.

---

README.md
internal/reload.go
main.go
test/corectl_integration_test.go
test/golden/project1-reload.golden
test/golden/project2-reload.golden
test/golden/project3-reload.golden

Only log reload progress if verbose logging is enabled

---

internal/state.go
main.go
printer/status.go
test/golden/project3-fields.golden
test/golden/project3-reload.golden

Separate error message when specifying engine explicitly

Added better error message when no connections can be made to engine

---

.editorconfig
README.md
main.go

* Adding newline to version command
* Adding a simple editorconfig
* Fixed lint errors in the README.md

Minor fixes

---

Gopkg.lock
Gopkg.toml
docs/corectl.md
docs/corectl_catwalk.md
internal/state.go
main.go
test/corectl_integration_test.go
test/golden/help-1.golden
test/golden/help-2.golden
test/golden/project1-catwalk-error.golden

This PR makes it possible to open catwalk from corectl.
The specified app will be opened. If no app is specified the hub in catwalk will be opened instead.
I have not added any integration test since we are not producing any text output and are using an external lib for opening the browser.
The creating of the URL is tested in the unit tests already.

Start catwalk from corectl

---

docs/corectl_get_apps.md
docs/corectl_get_dimensions.md
docs/corectl_get_measures.md
docs/corectl_get_objects.md
main.go
printer/apps.go
printer/entities.go
test/corectl_integration_test.go
test/golden/project1-measures-1-json.golden

Added json support for listing the measure, dimension and object lists
This closes #74 ?

Added json support for listing the measure, dimension and object lists

---

README.md
cmd/get.go
cmd/root.go
cmd/utils.go
docs/corectl_completion.md
printer/apps.go
printer/connections.go
printer/entities.go

This PR fixes two problems:
* Removes the need for having jq as dependency for auto completion
* Fixes problem with using flags and spaced argument during auto completion

Remove jq as dependency for auto completion

---

cmd/remove.go
cmd/root.go
docs/corectl_remove.md
docs/corectl_remove_connection.md
docs/corectl_remove_dimension.md
docs/corectl_remove_measure.md
docs/corectl_remove_object.md

Remove commands for connections, dimensions, measures and objects are now default singular and plural as alias.

Plural -> singular for remove commands

---

README.md
cmd/root.go
docs/spec.json

Also, changed so that the code completion snippet is a bit more robust.
Added instructions for aliasing corectl.

Change experimental to stable api

---

cmd/generate.go
cmd/unbuild.go
docs/corectl_unbuild.md
docs/spec.json

Added example for unbuild command

---

release.sh

Add pre-flight check for remote changes in release script

---

.gitignore
.goreleaser.yml

* Exclude commits for dependencies and image bumps from the changelog
* Add `dist` folder to .gitignore

Exclude specific commit patterns from changelog

---

go.mod
go.sum

Bumping to the version of enigma in which this issue is fixed.
Closes #346

Fix HTML-escaping

---

internal/connections.go
test/corectl_integration_test.go
test/projects/connections/connections-empty.yml
test/projects/connections/corectl-connectionsref-empty.yml

Handle separate connection files that are empty

---

internal/config.go
release.sh

Noted a faulty manually resolved merge conflict.

fix: Release pruning

---

cmd/analyze.go
cmd/completion.go
docs/corectl_fields.md
docs/spec.json
printer/fields.go
printer/mode.go

Quiet flag for `corectl fields` and bash-completion for `corectl values`.

feature: Add quiet-flag for fields and bash-completion for values

---

internal/unbuilder.go
internal/unbuilder_test.go
test/golden/TestTrafficFlag_script_get_--traffic.golden

fix: Add unbuild support for all unicode letters

---

internal/state.go

Adding a proper error message for x509 error
Closes #443

Fix error message

---

cmd/analyze.go
cmd/app.go
internal/eval.go
internal/field.go
internal/modeldata.go
pkg/log/log.go
pkg/rest/app.go
pkg/rest/rest_caller.go
printer/alternate_states.go
printer/apps.go
printer/connections.go
printer/entities.go
printer/fields.go
printer/printer.go
test/clientcommand/main.go

The log package is now responsible for all logging, meaning all information that is not intended to be consumed programmatically. It will be output to std error.
The printer package is responsible for all output meant to be consumed, basically, all information that is the actual output from commands.

Log and print

---

cmd/root.go
pkg/boot/boot.go
pkg/boot/flags.go
pkg/dynconf/dyn_settings_test.go
pkg/rest/app.go
test/clientcommand/main.go

Further improved error reporting when app flag is missing

Made it possible to move app flag to a non-global location

---

pkg/commands/standard/raw.go
pkg/rest/rest_caller.go

Change so that errors are returned instead of printed to `stdout`.
Also, cleanup output-file on failing raw-calls.

Don't print errors from rest calls to stdout

---

docs/corectl_raw.md
docs/spec.json
pkg/commands/standard/raw.go
pkg/rest/rest_caller.go

Polish some things related to the raw command.
- Add completion
- Add quiet flag
- Handle absolute redirect paths.

Polish raw command

---

docs/corectl_bookmark_layout.md
pkg/boot/flags.go
pkg/commands/engine/alternate_state.go
pkg/commands/engine/analyze.go
pkg/commands/engine/app.go
pkg/commands/engine/bookmark.go
pkg/commands/engine/connection.go
pkg/commands/engine/dimension.go
pkg/commands/engine/measure.go
pkg/commands/engine/object.go
pkg/commands/engine/variable.go

Added completion functions for all engine commands and the app flag

New completion functions

---

docs/corectl.md
docs/corectl_context.md
docs/corectl_context_init.md
docs/corectl_raw.md
docs/spec.json
pkg/commands/login/init.go
pkg/commands/standard/raw.go
test/golden/TestHelp_#00.golden
test/golden/TestHelp_help.golden

Changing naming to comply with the new marketing names.
Fails due to need to update engine

Fix prod naming

---

pkg/rest/rest_caller.go
pkg/rest/utils.go

Multipart logs
